module.exports = {
  // text (except for js and json that actually have application type)
  ".html": "text/html",
  ".htm": "text/html",
  ".css": "text/css",
  ".js": "application/javascript",
  ".json": "application/json",
  ".xml":  "text/xml",
  ".txt":  "text/plain",
  // images
  ".jpg":  "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png":  "image/png",
  ".ico":  "image/x-icon",
  ".gif":  "image/gif",
  ".svg": "image/svg+xml"
  ".bmp":  "image/bmp",
  ".tif":  "image/tiff",
  ".tiff": "image/tiff",
  // audio
  ".mp3":  "audio/mpeg3",
  ".mpa":  "audio/mpeg",
  ".oga": "audio/ogg",
  ".wav":  "audio/wav",
  // video
  ".mp4": "video/mp4",
  ".mp4v": "video/mp4",
  ".mpg4": "video/mp4",
  ".avi":  "video/avi",
  ".mov":  "video/quicktime",
  ".mpeg": "video/mpeg",
  ".mpg": "video/mpeg",
  ".mpe": "video/mpeg",
  ".m1v": "video/mpeg",
  ".m2v": "video/mpeg",
  ".ogv": "video/ogg",
  ".webm": "video/webm",
  // applications
  ".ogg": "application/ogg",
  ".pdf": "application/pdf",
  ".doc": "application/msword"
}
